networks:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:1.26.4
    container_name: gitea
    restart: always
    networks:
      - gitea
    ports:
      - "127.0.0.1:10624:3000"
    environment:
      - APP_NAME=${APP_NAME}
      - DB_TYPE=${DB_TYPE}
      - DISABLE_SSH=${DISABLE_SSH}
      - DISABLE_REGISTRATION=${DISABLE_REGISTRATION}
      - USER_UID=${USER_UID:-1000}
      - USER_GID=${USER_GID:-1000}

      # 配置并覆盖 custom/conf/app.ini
      # GITEA__SECTION_NAME__KEY_NAME=value
      - GITEA__i18n__LANGS=${GITEA_I18N_LANGS}
      - GITEA__i18n__NAMES=${GITEA_I18N_NAMES}
      - GITEA__ui__DEFAULT_THEME=${GITEA_THEME}
      - GITEA__time__FORMAT=${GITEA_TIME_FORMAT}
      - GITEA__time__DEFAULT_UI_LOCATION=${GITEA_TIME_LOCATION}
      - GITEA__server__ROOT_URL=${GITEA_ROOT_URL}
      - GITEA__server__LFS_START_SERVER=${GITEA_ENABLE_LFS}
      - GITEA__openid__ENABLE_OPENID_SIGNIN=${GITEA_ENABLE_OPENID_SIGNIN}
      - GITEA__openid__ENABLE_OPENID_SIGNUP=${GITEA_ENABLE_OPENID_SIGNUP}
      - GITEA__other__ENABLE_SITEMAP=${GITEA_ENABLE_SITEMAP}
      - GITEA__other__ENABLE_FEED=${GITEA_ENABLE_FEED}
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: "${LIMITS_CPUS:-1.0}"
          memory: "${LIMITS_MEMORY:-1024M}"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/api/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
